### ISSUE TITLE
How much does this new 23 edition differs from the 20 one?

### ISSUE THREAD

**Issue by name12surname34** [Apress/beginning-cpp23#18]
I don't know if it's the right place to ask, but I didn't find any other way to contact you. So, how much do they differ? What are some of the major differences?

**Comment by Peter-VanWeert** [comment]
Yes and no. Of course, C++23 is not the same paradigm shift as C++20 (modules, concepts, etc) and C++11 were, there's no denying that. So don't expect any "major", groundbreaking differences. But we did spend a significant amount of time improving the book. Even if C++23 is more a (surprisingly) long series of smaller improvements, some of which are particularly nice to have (of the top of my head: std::println(), import std, contains() functions, std::ranges::to<>(), the list goes on). Overall, there's not a single example that's not more elegant because of this. And C++23 not being a "major" language update, did give us time to work out some new sections that were missing and/or that readers have been asking about (of the top of my head: constexpr, consteval, if constexpr, ...).

**Comment by name12surname34** [comment]
Oh, ok. Is there any chance the book is going to be released before the current release date?

**Comment by Peter-VanWeert** [comment]
Who knows. But it won't be for immediately. Still a few weeks left for the first draft, then a couple for the second draft (provided nothing major was found during review), after which it goes to the editor (out of my control from here on out), then typesetting, a few rounds of proof reading, printing, distributing...

**Comment by darkonaito** [comment]
Hi, sorry if I bother you again: is a C++23 Standard Library Quick Reference planned?

**Comment by Peter-VanWeert** [comment]
It is, although the timeline is unclear. We actually started on it a long time ago (November 2021), but the project is on hold. I've been working on Beginning C++23 over the past months, Marc on Professional C++23 with Wiley. And both of us will for sure want a short break from writing after these demanding projects. But, until further notice, the plan is still to finish C++23 Standard Library Quick Reference (somewhere in 2024 if I were to guess, given that Marc's book is still some months work...).
